export type ElectricalAbilityItem = {
  text: string;
  dimension:
    | "SAYISAL"
    | "SOZEL"
    | "SOYUT"
    | "DIKKAT";
  difficulty:
    | "KOLAY"
    | "ORTA"
    | "ZOR";
  options: {
    key: string;
    text: string;
  }[];
  correctKey: string;
};

export const ELECTRICAL_MAINTENANCE_ABILITY_ITEMS_A: ElectricalAbilityItem[] = [
  {
    text: "Bir ekip 6 elektrik panosunu kontrol ediyor. Her panoda 8 bağlantı noktası varsa toplam kaç bağlantı noktası kontrol edilir?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "42" },
      { key: "B", text: "48" },
      { key: "C", text: "54" },
      { key: "D", text: "56" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir çalışma 08:30'da başlayıp 12:00'de bitiyor. Çalışma süresi kaç saattir?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "3,5" },
      { key: "C", text: "4" },
      { key: "D", text: "4,5" },
    ],
    correctKey: "B",
  },
  {
    text: "200 bağlantının 50 tanesi kontrol edilmiştir. Kontrol edilenlerin toplam içindeki oranı nedir?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir ekip üç günde sırasıyla 24, 30 ve 36 kontrol yapmıştır. Günlük ortalama kaç kontrol yapılmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "28" },
      { key: "B", text: "30" },
      { key: "C", text: "32" },
      { key: "D", text: "34" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir ölçüm değeri 80'den 100'e çıkmıştır. Artış oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "4 çalışan toplam 60 bağlantı kontrol ediyor. Aynı iş 5 çalışan arasında eşit paylaştırılırsa kişi başına kaç bağlantı düşer?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "10" },
      { key: "B", text: "12" },
      { key: "C", text: "15" },
      { key: "D", text: "20" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir depoda 300 sigorta bulunmaktadır. 75'i kullanılmıştır. Kaç sigorta kalmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "215" },
      { key: "B", text: "225" },
      { key: "C", text: "235" },
      { key: "D", text: "245" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kontrol işlemi 15 dakika sürmektedir. Aynı işlem 6 kez yapılırsa toplam süre kaç dakika olur?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "75" },
      { key: "B", text: "90" },
      { key: "C", text: "105" },
      { key: "D", text: "120" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir değerin 150'den 120'ye düşmesi yüzde kaç azalmadır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%15" },
      { key: "B", text: "%20" },
      { key: "C", text: "%25" },
      { key: "D", text: "%30" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kontrol planının ilk gün %30'u tamamlanıyor. İkinci gün kalan işin %50'si tamamlanıyor. İki gün sonunda toplam işin yüzde kaçı tamamlanmıştır?",
    dimension: "SAYISAL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "%55" },
      { key: "B", text: "%60" },
      { key: "C", text: "%65" },
      { key: "D", text: "%70" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Kontrol\" kelimesine en yakın anlam hangisidir?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "İnceleme" },
      { key: "B", text: "Bekleme" },
      { key: "C", text: "Taşıma" },
      { key: "D", text: "Saklama" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışmaya başlamadan önce verilen talimatı ______.",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "okumalıyız" },
      { key: "B", text: "değiştirmeliyiz" },
      { key: "C", text: "kaldırmalıyız" },
      { key: "D", text: "ertelemeliyiz" },
    ],
    correctKey: "A",
  },
  {
    text: "Hangisi diğerlerinden farklı bir gruptadır?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Kablo" },
      { key: "B", text: "Sigorta" },
      { key: "C", text: "Klemens" },
      { key: "D", text: "Baret" },
    ],
    correctKey: "D",
  },
  {
    text: "\"Kontrol – Eksiklik\" ilişkisine en yakın ilişki hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İnceleme – Hata" },
      { key: "B", text: "Hız – Bekleme" },
      { key: "C", text: "Başlangıç – Bitiş" },
      { key: "D", text: "Gürültü – Sessizlik" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışan, yapacağı işlemin sırasından emin olmadığı için işe başlamadan önce sorumlusuna danışıyor. Bu davranış neyi gösterir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İşi yapmak istemediğini" },
      { key: "B", text: "Doğru yöntemi netleştirdiğini" },
      { key: "C", text: "İşi başkasına bıraktığını" },
      { key: "D", text: "Kontrolü gereksiz gördüğünü" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Tedbir\" sözcüğüne en yakın anlam hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Önlem" },
      { key: "B", text: "Gecikme" },
      { key: "C", text: "Değişiklik" },
      { key: "D", text: "Bekleme" },
    ],
    correctKey: "A",
  },
  {
    text: "\"önce / kontrol / enerjiyi / işlemden / et\" kelimeleriyle kurulacak anlamlı cümlenin ilk kelimesi hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Önce" },
      { key: "B", text: "Kontrol" },
      { key: "C", text: "Enerjiyi" },
      { key: "D", text: "İşlemden" },
    ],
    correctKey: "D",
  },
  {
    text: "Talimat, işlem tamamlandıktan sonra kullanılan araçların belirlenen yere bırakılmasını istiyor. Çalışan ne yapmalıdır?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Araçları çalışma alanında bırakmalı" },
      { key: "B", text: "Araçları belirlenen yere koymalı" },
      { key: "C", text: "Araçları başka çalışana vermeli" },
      { key: "D", text: "Talimatı dikkate almamalı" },
    ],
    correctKey: "B",
  },
  {
    text: "Yapılan kontrollerin ve tespit edilen eksikliklerin kaydedilmesi sonraki çalışmalarda ne yapıldığının anlaşılmasını kolaylaştırır. Ana düşünce nedir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Kayıt tutmak işin takibini kolaylaştırır." },
      { key: "B", text: "Her kontrol uzun sürer." },
      { key: "C", text: "Eksiklikler kaydedilmemelidir." },
      { key: "D", text: "Çalışanlar yalnız çalışmalıdır." },
    ],
    correctKey: "A",
  },
  {
    text: "Bir işlemin hızlı tamamlanması önemlidir; ancak gerekli kontroller yapılmadan çalışmaya devam edilmesi hata ve güvenlik riski oluşturabilir. Bu ifadeyi en iyi özetleyen seçenek hangisidir?",
    dimension: "SOZEL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "Hız her zaman kontrolden önemlidir." },
      { key: "B", text: "Kontrol yalnız hata olduğunda yapılmalıdır." },
      { key: "C", text: "Hızın yanında doğru işlem ve kontrol de önemlidir." },
      { key: "D", text: "Kontroller işi gereksiz yere uzatır." },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: B, D, F, H, ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "I" },
      { key: "B", text: "J" },
      { key: "C", text: "K" },
      { key: "D", text: "L" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: ▲ ● ▲ ● ▲ ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "▲" },
      { key: "B", text: "●" },
      { key: "C", text: "■" },
      { key: "D", text: "◆" },
    ],
    correctKey: "B",
  },
  {
    text: "3A, 6B, 9C, 12D dizisinde sıradaki öğe hangisidir?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "14E" },
      { key: "B", text: "15D" },
      { key: "C", text: "15E" },
      { key: "D", text: "18E" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kuralda A=3, B=6, C=9, D=12 ise G'nin değeri kaçtır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "18" },
      { key: "B", text: "21" },
      { key: "C", text: "24" },
      { key: "D", text: "27" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 5, 9, 14, 20, 27, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "33" },
      { key: "B", text: "34" },
      { key: "C", text: "35" },
      { key: "D", text: "36" },
    ],
    correctKey: "C",
  },
  {
    text: "KL → LK, MN → NM kuralına göre PR nasıl yazılır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "PR" },
      { key: "B", text: "RP" },
      { key: "C", text: "PP" },
      { key: "D", text: "RR" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kuralda her sayı önce 3 ile çarpılıyor, sonra 2 çıkarılıyor. 6 sayısına uygulanırsa sonuç kaç olur?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "14" },
      { key: "B", text: "16" },
      { key: "C", text: "18" },
      { key: "D", text: "20" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: Y, V, S, P, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "M" },
      { key: "B", text: "N" },
      { key: "C", text: "O" },
      { key: "D", text: "L" },
    ],
    correctKey: "A",
  },
  {
    text: "Diziyi tamamlayın: 2, 6, 24, 120, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "360" },
      { key: "B", text: "480" },
      { key: "C", text: "600" },
      { key: "D", text: "720" },
    ],
    correctKey: "D",
  },
  {
    text: "Dizide sıradaki sayı hangisidir? 4, 7, 11, 18, 29, 47, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "65" },
      { key: "B", text: "72" },
      { key: "C", text: "76" },
      { key: "D", text: "78" },
    ],
    correctKey: "B",
  },
  {
    text: 'Hangisi "EL-4826-K" koduyla birebir aynıdır?',
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "EL-4826-K" },
      { key: "B", text: "EL-4286-K" },
      { key: "C", text: "EL-4826-X" },
      { key: "D", text: "EL-482G-K" },
    ],
    correctKey: "A",
  },
  {
    text: "Şu dizide E harfi kaç kez geçmektedir? E K E R T E K E M T E",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangisi diğerlerinden farklı yazılmıştır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "KLEMENS" },
      { key: "B", text: "KLEMENS" },
      { key: "C", text: "KLEMNES" },
      { key: "D", text: "KLEMENS" },
    ],
    correctKey: "C",
  },
  {
    text: "Kaç satır tamamen aynıdır? Liste 1: EL-214 / PN-583 / KR-407 / TR-625. Liste 2: EL-214 / PN-538 / KR-407 / TR-652.",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: 'Hangisi "EP-7315-A4" koduyla aynı değildir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "EP-7315-A4" },
      { key: "B", text: "EP-7315-A4" },
      { key: "C", text: "EP-7135-A4" },
      { key: "D", text: "EP-7315-A4" },
    ],
    correctKey: "C",
  },
  {
    text: "Şu dizide 6 rakamı kaç kez geçmektedir? 6 3 6 8 1 6 4 2 6 5 6",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangi sayı grubunun rakam sırası diğerlerinden farklıdır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "58324" },
      { key: "B", text: "58324" },
      { key: "C", text: "53824" },
      { key: "D", text: "58324" },
    ],
    correctKey: "C",
  },
  {
    text: "125, 152, 215, 251, 512, 521 değerlerinin kaç tanesi 5 rakamıyla başlamaktadır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: '"EL7-K29-X" kodunun aynısı hangisidir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "EL7-K92-X" },
      { key: "B", text: "EL7-K29-X" },
      { key: "C", text: "EL7-X29-K" },
      { key: "D", text: "EL7-K29-Y" },
    ],
    correctKey: "B",
  },
  {
    text: "İki satır arasında kaç karakter farklıdır? A: E7K4P9R2T5  B: E7M4P6R2T8",
    dimension: "DIKKAT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "2" },
      { key: "B", text: "3" },
      { key: "C", text: "4" },
      { key: "D", text: "5" },
    ],
    correctKey: "B",
  },
];

export const ELECTRICAL_MAINTENANCE_ABILITY_ITEMS_B: ElectricalAbilityItem[] = [
  {
    text: "Bir ekip 8 panonun her birinde 6 bağlantı noktası kontrol ediyor. Toplam kaç bağlantı noktası kontrol edilir?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "42" },
      { key: "B", text: "48" },
      { key: "C", text: "54" },
      { key: "D", text: "56" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir çalışma 09:00'da başlayıp 12:30'da tamamlanıyor. Çalışma kaç saat sürmüştür?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "3,5" },
      { key: "C", text: "4" },
      { key: "D", text: "4,5" },
    ],
    correctKey: "B",
  },
  {
    text: "160 bağlantının 40 tanesi kontrol edilmiştir. Kontrol edilenlerin oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir ekip üç vardiyada sırasıyla 28, 32 ve 40 kontrol yapmıştır. Vardiya başına ortalama kaç kontrol yapılmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "30" },
      { key: "B", text: "32" },
      { key: "C", text: "34" },
      { key: "D", text: "36" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir ölçüm değeri 120'den 150'ye çıkmıştır. Artış oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%35" },
    ],
    correctKey: "B",
  },
  {
    text: "5 çalışan toplam 75 kontrol yapıyor. Aynı toplam iş 3 çalışan arasında eşit paylaştırılırsa kişi başına kaç kontrol düşer?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "20" },
      { key: "B", text: "25" },
      { key: "C", text: "30" },
      { key: "D", text: "35" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir depoda 280 parça vardır. 90 parça kullanılmıştır. Kaç parça kalmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "180" },
      { key: "B", text: "190" },
      { key: "C", text: "200" },
      { key: "D", text: "210" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kontrol 20 dakika sürüyor. Aynı işlem 6 kez yapılırsa toplam süre kaç saat olur?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1 saat 40 dakika" },
      { key: "B", text: "2 saat" },
      { key: "C", text: "2 saat 20 dakika" },
      { key: "D", text: "2 saat 40 dakika" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir değer 240'tan 192'ye düşmüştür. Azalma oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%15" },
      { key: "B", text: "%20" },
      { key: "C", text: "%25" },
      { key: "D", text: "%30" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kontrol planının ilk gün %35'i tamamlanıyor. İkinci gün kalan işin %40'ı tamamlanıyor. İki gün sonunda toplam işin yüzde kaçı tamamlanmıştır?",
    dimension: "SAYISAL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "%55" },
      { key: "B", text: "%61" },
      { key: "C", text: "%65" },
      { key: "D", text: "%70" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Talimat\" kelimesine en yakın anlam hangisidir?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Yönerge" },
      { key: "B", text: "Malzeme" },
      { key: "C", text: "Ölçüm" },
      { key: "D", text: "Bekleme" },
    ],
    correctKey: "A",
  },
  {
    text: "Bir işleme başlamadan önce çalışma alanını ______.",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "kontrol etmeliyiz" },
      { key: "B", text: "terk etmeliyiz" },
      { key: "C", text: "dağıtmalıyız" },
      { key: "D", text: "kapatmalıyız" },
    ],
    correctKey: "A",
  },
  {
    text: "Hangisi diğerlerinden farklı bir gruptadır?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Kablo" },
      { key: "B", text: "Klemens" },
      { key: "C", text: "Sigorta" },
      { key: "D", text: "Eldiven" },
    ],
    correctKey: "D",
  },
  {
    text: "\"Kontrol – Güvenlik\" ilişkisine en yakın ilişki hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Önlem – Risk" },
      { key: "B", text: "Hız – Bekleme" },
      { key: "C", text: "Başlangıç – Bitiş" },
      { key: "D", text: "Gürültü – Sessizlik" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışan, verilen iş emrinde anlamadığı bir bölüm olduğunu fark ediyor ve işe başlamadan önce sorumlusuna soruyor. Bu davranış neyi gösterir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İşi yapmak istemediğini" },
      { key: "B", text: "Talimatı doğru anlamaya çalıştığını" },
      { key: "C", text: "İşi başkasına devrettiğini" },
      { key: "D", text: "Kontrolü gereksiz gördüğünü" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Uygunsuzluk\" kelimesine en yakın ifade hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Beklenenden sapma" },
      { key: "B", text: "Hızlı çalışma" },
      { key: "C", text: "İş bölümü" },
      { key: "D", text: "Dinlenme" },
    ],
    correctKey: "A",
  },
  {
    text: "\"işlemden / önce / gerekli / kontrolleri / yap\" kelimeleriyle kurulacak anlamlı cümlenin ilk kelimesi hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İşlemden" },
      { key: "B", text: "Önce" },
      { key: "C", text: "Gerekli" },
      { key: "D", text: "Kontrolleri" },
    ],
    correctKey: "A",
  },
  {
    text: "İş tamamlandıktan sonra kullanılan araç ve malzemelerin yerine bırakılması neden önemlidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Düzeni ve sonraki kullanımı kolaylaştırır." },
      { key: "B", text: "İşin daha uzun sürmesini sağlar." },
      { key: "C", text: "Malzemelerin kullanılmasını engeller." },
      { key: "D", text: "Kontrol ihtiyacını ortadan kaldırır." },
    ],
    correctKey: "A",
  },
  {
    text: "Bir çalışan kontrolde beklenmeyen bir durum fark ettiğinde işlemi durdurup sorumlusuna bilgi veriyor. Bu davranışın temel amacı nedir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Olası hatayı veya riski büyümeden değerlendirmek" },
      { key: "B", text: "İşi başka çalışana bırakmak" },
      { key: "C", text: "Çalışmayı geciktirmek" },
      { key: "D", text: "Kontrol yapmaktan kaçınmak" },
    ],
    correctKey: "A",
  },
  {
    text: "Bir işlemin kısa sürede tamamlanması olumlu olabilir. Ancak doğru sıra izlenmeden ve gerekli kontroller yapılmadan tamamlanan işlem güvenilir kabul edilemez. Bu ifadeyi en iyi hangisi özetler?",
    dimension: "SOZEL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "Hız her koşulda en önemli ölçüttür." },
      { key: "B", text: "Kontroller yalnız sorun çıktığında yapılmalıdır." },
      { key: "C", text: "Hız kadar doğru yöntem ve kontrol de önemlidir." },
      { key: "D", text: "İş sırasının sonuca etkisi yoktur." },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: A, C, E, G, ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "H" },
      { key: "B", text: "I" },
      { key: "C", text: "J" },
      { key: "D", text: "K" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: ■ ● ■ ● ■ ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "■" },
      { key: "B", text: "●" },
      { key: "C", text: "▲" },
      { key: "D", text: "◆" },
    ],
    correctKey: "B",
  },
  {
    text: "2A, 4B, 6C, 8D dizisinde sıradaki öğe hangisidir?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "9E" },
      { key: "B", text: "10D" },
      { key: "C", text: "10E" },
      { key: "D", text: "12E" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kuralda A=4, B=8, C=12, D=16 ise F'nin değeri kaçtır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "20" },
      { key: "B", text: "24" },
      { key: "C", text: "28" },
      { key: "D", text: "32" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 3, 7, 12, 18, 25, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "31" },
      { key: "B", text: "32" },
      { key: "C", text: "33" },
      { key: "D", text: "34" },
    ],
    correctKey: "C",
  },
  {
    text: "PQ → QP, RS → SR kuralına göre TU nasıl yazılır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "TU" },
      { key: "B", text: "UT" },
      { key: "C", text: "TT" },
      { key: "D", text: "UU" },
    ],
    correctKey: "B",
  },
  {
    text: "Her sayı önce 2 ile çarpılıyor, sonra 4 ekleniyor. 8 sayısına uygulanırsa sonuç kaç olur?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "16" },
      { key: "B", text: "18" },
      { key: "C", text: "20" },
      { key: "D", text: "24" },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: Z, W, T, Q, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "N" },
      { key: "B", text: "O" },
      { key: "C", text: "P" },
      { key: "D", text: "M" },
    ],
    correctKey: "A",
  },
  {
    text: "Diziyi tamamlayın: 1, 3, 12, 60, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "180" },
      { key: "B", text: "240" },
      { key: "C", text: "300" },
      { key: "D", text: "360" },
    ],
    correctKey: "D",
  },
  {
    text: "Dizide sıradaki sayı hangisidir? 3, 5, 8, 13, 21, 34, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "47" },
      { key: "B", text: "52" },
      { key: "C", text: "55" },
      { key: "D", text: "57" },
    ],
    correctKey: "C",
  },
  {
    text: 'Hangisi "EL-6934-R" koduyla birebir aynıdır?',
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "EL-6934-R" },
      { key: "B", text: "EL-6394-R" },
      { key: "C", text: "EL-6934-P" },
      { key: "D", text: "EL-693A-R" },
    ],
    correctKey: "A",
  },
  {
    text: "Şu dizide K harfi kaç kez geçmektedir? K M R K T K M K R T K",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangisi diğerlerinden farklı yazılmıştır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "SIGORTA" },
      { key: "B", text: "SIGORTA" },
      { key: "C", text: "SIGROTA" },
      { key: "D", text: "SIGORTA" },
    ],
    correctKey: "C",
  },
  {
    text: "Kaç satır tamamen aynıdır? Liste 1: EA-124 / KM-583 / TR-907 / PN-441. Liste 2: EA-124 / KM-538 / TR-907 / PN-414.",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: 'Hangisi "EK-8305-B2" koduyla aynı değildir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "EK-8305-B2" },
      { key: "B", text: "EK-8305-B2" },
      { key: "C", text: "EK-8035-B2" },
      { key: "D", text: "EK-8305-B2" },
    ],
    correctKey: "C",
  },
  {
    text: "Şu dizide 9 rakamı kaç kez geçmektedir? 9 4 9 2 7 9 1 9 6 3 9",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangi sayı grubunun rakam sırası diğerlerinden farklıdır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "62418" },
      { key: "B", text: "62418" },
      { key: "C", text: "64218" },
      { key: "D", text: "62418" },
    ],
    correctKey: "C",
  },
  {
    text: "217, 271, 712, 721, 127, 172 değerlerinin kaç tanesi 7 rakamıyla başlamaktadır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: '"EL8-P36-M" kodunun aynısı hangisidir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "EL8-P63-M" },
      { key: "B", text: "EL8-P36-M" },
      { key: "C", text: "EL8-R36-M" },
      { key: "D", text: "EL8-P36-N" },
    ],
    correctKey: "B",
  },
  {
    text: "İki satır arasında kaç karakter farklıdır? A: K8M3P7R4T6  B: K8N3P2R4T9",
    dimension: "DIKKAT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "2" },
      { key: "B", text: "3" },
      { key: "C", text: "4" },
      { key: "D", text: "5" },
    ],
    correctKey: "B",
  },
];