export type LaboratoryAbilityItem = {
  text: string;
  dimension:
    | "SAYISAL"
    | "SOZEL"
    | "SOYUT"
    | "DIKKAT";
  difficulty:
    | "KOLAY"
    | "ORTA"
    | "ZOR";
  options: {
    key: string;
    text: string;
  }[];
  correctKey: string;
};

export const LABORATORY_WORKER_ABILITY_ITEMS_A: LaboratoryAbilityItem[] = [
  {
    text: "Bir laboratuvarda 6 tepsinin her birinde 10 numune vardır. Toplam kaç numune vardır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "50" },
      { key: "B", text: "60" },
      { key: "C", text: "70" },
      { key: "D", text: "80" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir çalışma 08:00'de başlayıp 11:30'da bitiyor. Çalışma süresi kaç saattir?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "3,5" },
      { key: "C", text: "4" },
      { key: "D", text: "4,5" },
    ],
    correctKey: "B",
  },
  {
    text: "200 numunenin 50 tanesi kontrol edilmiştir. Kontrol edilenler toplamın yüzde kaçıdır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "Üç kontrol sırasıyla 20, 30 ve 40 dakika sürmüştür. Ortalama kontrol süresi kaç dakikadır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "25" },
      { key: "B", text: "30" },
      { key: "C", text: "35" },
      { key: "D", text: "40" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir malzemenin miktarı 80 adetten 100 adede çıkmıştır. Artış oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "5 çalışan toplam 60 numune hazırlıyor. Aynı toplam iş 4 çalışan arasında eşit paylaştırılırsa kişi başına kaç numune düşer?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "12" },
      { key: "B", text: "15" },
      { key: "C", text: "16" },
      { key: "D", text: "20" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir rafta 240 numune kabı vardır. 65 tanesi kullanılmıştır. Kaç tane kalmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "165" },
      { key: "B", text: "175" },
      { key: "C", text: "185" },
      { key: "D", text: "195" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kontrol işlemi 15 dakika sürüyor. Aynı işlem 8 kez yapılırsa toplam süre kaç saat olur?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1 saat" },
      { key: "B", text: "2 saat" },
      { key: "C", text: "2 saat 15 dakika" },
      { key: "D", text: "2 saat 30 dakika" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir değerin 180'den 144'e düşmesi yüzde kaç azalmadır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%15" },
      { key: "B", text: "%20" },
      { key: "C", text: "%25" },
      { key: "D", text: "%30" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir numune kontrol planının ilk gün %40'ı tamamlanıyor. İkinci gün kalan işin %50'si tamamlanıyor. İki gün sonunda toplam işin yüzde kaçı tamamlanmıştır?",
    dimension: "SAYISAL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "%60" },
      { key: "B", text: "%65" },
      { key: "C", text: "%70" },
      { key: "D", text: "%75" },
    ],
    correctKey: "C",
  },
  {
    text: "\"Talimat\" kelimesine en yakın anlam hangisidir?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Yönerge" },
      { key: "B", text: "Malzeme" },
      { key: "C", text: "Bekleme" },
      { key: "D", text: "Ölçüm" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışmaya başlamadan önce verilen talimatı ______.",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "okumalıyız" },
      { key: "B", text: "değiştirmeliyiz" },
      { key: "C", text: "kaldırmalıyız" },
      { key: "D", text: "ertelemeliyiz" },
    ],
    correctKey: "A",
  },
  {
    text: "Hangisi diğerlerinden farklıdır?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Numune kabı" },
      { key: "B", text: "Etiket" },
      { key: "C", text: "Laboratuvar formu" },
      { key: "D", text: "Baret" },
    ],
    correctKey: "D",
  },
  {
    text: "\"Kontrol – Hata\" ilişkisine en yakın ilişki hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İnceleme – Eksiklik" },
      { key: "B", text: "Hız – Bekleme" },
      { key: "C", text: "Başlangıç – Bitiş" },
      { key: "D", text: "Gürültü – Sessizlik" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışan, bir formdaki bilgiyi tam anlamadığı için kayıt yapmadan önce sorumlusuna danışıyor. Bu davranış neyi gösterir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İşi yapmak istemediğini" },
      { key: "B", text: "Bilgiyi doğru anlamaya çalıştığını" },
      { key: "C", text: "İşi başkasına bıraktığını" },
      { key: "D", text: "Kayıt tutmak istemediğini" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Uygunsuzluk\" sözcüğüne en yakın ifade hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Beklenenden sapma" },
      { key: "B", text: "Hızlı çalışma" },
      { key: "C", text: "İş bölümü" },
      { key: "D", text: "Dinlenme" },
    ],
    correctKey: "A",
  },
  {
    text: "\"önce / etiketi / kontrol / numunenin / et\" kelimeleriyle kurulacak anlamlı cümlenin ilk kelimesi hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Önce" },
      { key: "B", text: "Etiketi" },
      { key: "C", text: "Kontrol" },
      { key: "D", text: "Numunenin" },
    ],
    correctKey: "A",
  },
  {
    text: "Numune alındıktan sonra etiket bilgilerinin kontrol edilmesi neden önemlidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Numunenin doğru şekilde takip edilmesini sağlar." },
      { key: "B", text: "İşi gereksiz yere uzatır." },
      { key: "C", text: "Kayıt yapılmasını engeller." },
      { key: "D", text: "Numunenin kullanılmasını önler." },
    ],
    correctKey: "A",
  },
  {
    text: "Bir çalışan kontrol sırasında beklenmeyen bir durum fark ediyor ve sonucu kaydetmeden önce sorumlusuna bilgi veriyor. Bu davranış neyi gösterir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Durumu doğru şekilde değerlendirmeye çalıştığını" },
      { key: "B", text: "İşi yapmak istemediğini" },
      { key: "C", text: "Çalışmayı bırakmak istediğini" },
      { key: "D", text: "Kayıt tutmaktan kaçındığını" },
    ],
    correctKey: "A",
  },
  {
    text: "Bir laboratuvar işleminde hızlı olmak önemlidir. Ancak numune, kayıt ve kontrol adımlarının doğru sırayla yapılması daha güvenilir sonuç sağlar. En iyi özet hangisidir?",
    dimension: "SOZEL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "En önemli şey işlemi en hızlı tamamlamaktır." },
      { key: "B", text: "Kontroller yalnız hata çıkınca yapılmalıdır." },
      { key: "C", text: "Hızın yanında doğru sıra ve kontrol de önemlidir." },
      { key: "D", text: "Kayıt tutmak gereksizdir." },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: A, C, E, G, ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "H" },
      { key: "B", text: "I" },
      { key: "C", text: "J" },
      { key: "D", text: "K" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: ● ■ ● ■ ● ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "●" },
      { key: "B", text: "■" },
      { key: "C", text: "▲" },
      { key: "D", text: "◆" },
    ],
    correctKey: "B",
  },
  {
    text: "5A, 10B, 15C, 20D dizisinde sıradaki öğe hangisidir?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "20E" },
      { key: "B", text: "25D" },
      { key: "C", text: "25E" },
      { key: "D", text: "30E" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kuralda A=2, B=4, C=6, D=8 ise G'nin değeri kaçtır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "12" },
      { key: "B", text: "14" },
      { key: "C", text: "16" },
      { key: "D", text: "18" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 3, 6, 10, 15, 21, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "26" },
      { key: "B", text: "27" },
      { key: "C", text: "28" },
      { key: "D", text: "29" },
    ],
    correctKey: "C",
  },
  {
    text: "AB → BA, CD → DC kuralına göre EF nasıl yazılır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "EF" },
      { key: "B", text: "FE" },
      { key: "C", text: "EE" },
      { key: "D", text: "FF" },
    ],
    correctKey: "B",
  },
  {
    text: "Her sayı önce 2 ile çarpılıyor, sonra 5 ekleniyor. 6 sayısına uygulanırsa sonuç kaç olur?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "12" },
      { key: "B", text: "15" },
      { key: "C", text: "17" },
      { key: "D", text: "19" },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: X, U, R, O, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "M" },
      { key: "B", text: "L" },
      { key: "C", text: "K" },
      { key: "D", text: "N" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 2, 4, 12, 48, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "144" },
      { key: "B", text: "192" },
      { key: "C", text: "240" },
      { key: "D", text: "288" },
    ],
    correctKey: "C",
  },
  {
    text: "Dizide sıradaki sayı hangisidir? 2, 3, 5, 8, 13, 21, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "29" },
      { key: "B", text: "31" },
      { key: "C", text: "34" },
      { key: "D", text: "36" },
    ],
    correctKey: "C",
  },
  {
    text: 'Hangisi "LAB-4827-K" koduyla birebir aynıdır?',
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "LAB-4827-K" },
      { key: "B", text: "LAB-4287-K" },
      { key: "C", text: "LAB-4827-X" },
      { key: "D", text: "LAB-482T-K" },
    ],
    correctKey: "A",
  },
  {
    text: "Şu dizide N harfi kaç kez geçmektedir? N K N R T N K N M T N",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangisi diğerlerinden farklı yazılmıştır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "NUMUNE" },
      { key: "B", text: "NUMUNE" },
      { key: "C", text: "NUMUEN" },
      { key: "D", text: "NUMUNE" },
    ],
    correctKey: "C",
  },
  {
    text: "Kaç kod tamamen aynıdır? Liste 1: LA-214 / NM-583 / KR-407 / TR-625. Liste 2: LA-214 / NM-538 / KR-407 / TR-652.",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: 'Hangisi "NU-7315-A4" koduyla aynı değildir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "NU-7315-A4" },
      { key: "B", text: "NU-7315-A4" },
      { key: "C", text: "NU-7135-A4" },
      { key: "D", text: "NU-7315-A4" },
    ],
    correctKey: "C",
  },
  {
    text: "Şu dizide 8 rakamı kaç kez geçmektedir? 8 3 8 5 1 8 6 2 8 4 8",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangi sayı grubunun rakam sırası diğerlerinden farklıdır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "47216" },
      { key: "B", text: "47216" },
      { key: "C", text: "42716" },
      { key: "D", text: "47216" },
    ],
    correctKey: "C",
  },
  {
    text: "125, 152, 215, 251, 512, 521 değerlerinin kaç tanesi 5 rakamıyla başlamaktadır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: '"LB7-N25-R" kodunun aynısı hangisidir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "LB7-N52-R" },
      { key: "B", text: "LB7-N25-R" },
      { key: "C", text: "LB7-M25-R" },
      { key: "D", text: "LB7-N25-K" },
    ],
    correctKey: "B",
  },
  {
    text: "İki satır arasında kaç karakter farklıdır? A: L7K4N8R2T5  B: L7M4N3R2T9",
    dimension: "DIKKAT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "2" },
      { key: "B", text: "3" },
      { key: "C", text: "4" },
      { key: "D", text: "5" },
    ],
    correctKey: "B",
  },
];

export const LABORATORY_WORKER_ABILITY_ITEMS_B: LaboratoryAbilityItem[] = [
  {
    text: "Bir laboratuvarda 8 rafın her birinde 5 numune kabı vardır. Toplam kaç numune kabı vardır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "35" },
      { key: "B", text: "40" },
      { key: "C", text: "45" },
      { key: "D", text: "50" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir işlem 09:00'da başlayıp 12:30'da bitiyor. İşlem kaç saat sürmüştür?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "3,5" },
      { key: "C", text: "4" },
      { key: "D", text: "4,5" },
    ],
    correctKey: "B",
  },
  {
    text: "240 numunenin 60 tanesi kontrol edilmiştir. Kontrol edilenler toplamın yüzde kaçıdır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%35" },
    ],
    correctKey: "B",
  },
  {
    text: "Üç kontrol sırasıyla 25, 35 ve 40 dakika sürmüştür. Ortalama süre kaç dakikadır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "30" },
      { key: "B", text: "33,3" },
      { key: "C", text: "35" },
      { key: "D", text: "40" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir malzemenin miktarı 100 adetten 125 adede çıkmıştır. Artış oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%35" },
    ],
    correctKey: "B",
  },
  {
    text: "4 çalışan toplam 80 numune hazırlıyor. Aynı iş 5 çalışan arasında eşit paylaşılırsa kişi başına kaç numune düşer?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "12" },
      { key: "B", text: "16" },
      { key: "C", text: "20" },
      { key: "D", text: "24" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir depoda 350 numune kabı vardır. 125 tanesi kullanılmıştır. Kaç tane kalmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "215" },
      { key: "B", text: "225" },
      { key: "C", text: "235" },
      { key: "D", text: "245" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kontrol işlemi 20 dakika sürüyor. Aynı işlem 6 kez yapılırsa toplam süre kaç saat olur?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1 saat 40 dakika" },
      { key: "B", text: "2 saat" },
      { key: "C", text: "2 saat 20 dakika" },
      { key: "D", text: "2 saat 40 dakika" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir ölçüm değeri 200'den 160'a düşmüştür. Azalma oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%15" },
      { key: "B", text: "%20" },
      { key: "C", text: "%25" },
      { key: "D", text: "%30" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir numune kontrol planının ilk gün %30'u tamamlanıyor. İkinci gün kalan işin %50'si tamamlanıyor. İki gün sonunda toplam işin yüzde kaçı tamamlanmıştır?",
    dimension: "SAYISAL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "%55" },
      { key: "B", text: "%60" },
      { key: "C", text: "%65" },
      { key: "D", text: "%70" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Talimat\" kelimesine en yakın anlam hangisidir?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Yönerge" },
      { key: "B", text: "Malzeme" },
      { key: "C", text: "Bekleme" },
      { key: "D", text: "Ölçüm" },
    ],
    correctKey: "A",
  },
  {
    text: "Bir işleme başlamadan önce çalışma alanını ______.",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "kontrol etmeliyiz" },
      { key: "B", text: "terk etmeliyiz" },
      { key: "C", text: "dağıtmalıyız" },
      { key: "D", text: "kapatmalıyız" },
    ],
    correctKey: "A",
  },
  {
    text: "Hangisi diğerlerinden farklıdır?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Numune kabı" },
      { key: "B", text: "Etiket" },
      { key: "C", text: "Laboratuvar formu" },
      { key: "D", text: "Baret" },
    ],
    correctKey: "D",
  },
  {
    text: "\"Kontrol – Hata\" ilişkisine en yakın ilişki hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İnceleme – Eksiklik" },
      { key: "B", text: "Hız – Bekleme" },
      { key: "C", text: "Başlangıç – Bitiş" },
      { key: "D", text: "Gürültü – Sessizlik" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışan, bir formdaki bilgiyi tam anlamadığı için kayıt yapmadan önce sorumlusuna danışıyor. Bu davranış neyi gösterir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İşi yapmak istemediğini" },
      { key: "B", text: "Bilgiyi doğru anlamaya çalıştığını" },
      { key: "C", text: "İşi başkasına bıraktığını" },
      { key: "D", text: "Kayıt tutmak istemediğini" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Uygunsuzluk\" sözcüğüne en yakın ifade hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Beklenenden sapma" },
      { key: "B", text: "Hızlı çalışma" },
      { key: "C", text: "İş bölümü" },
      { key: "D", text: "Dinlenme" },
    ],
    correctKey: "A",
  },
  {
    text: "\"önce / etiketi / kontrol / numunenin / et\" kelimeleriyle kurulacak anlamlı cümlenin ilk kelimesi hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Önce" },
      { key: "B", text: "Etiketi" },
      { key: "C", text: "Kontrol" },
      { key: "D", text: "Numunenin" },
    ],
    correctKey: "A",
  },
  {
    text: "Numune alındıktan sonra etiket bilgilerinin kontrol edilmesi neden önemlidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Numunenin doğru şekilde takip edilmesini sağlar." },
      { key: "B", text: "İşi gereksiz yere uzatır." },
      { key: "C", text: "Kayıt yapılmasını engeller." },
      { key: "D", text: "Numunenin kullanılmasını önler." },
    ],
    correctKey: "A",
  },
  {
    text: "Bir çalışan kontrol sırasında beklenmeyen bir durum fark ediyor ve sonucu kaydetmeden önce sorumlusuna bilgi veriyor. Bu davranış neyi gösterir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Durumu doğru şekilde değerlendirmeye çalıştığını" },
      { key: "B", text: "İşi yapmak istemediğini" },
      { key: "C", text: "Çalışmayı bırakmak istediğini" },
      { key: "D", text: "Kayıt tutmaktan kaçındığını" },
    ],
    correctKey: "A",
  },
  {
    text: "Bir laboratuvar işleminde hızlı olmak önemlidir. Ancak numune, kayıt ve kontrol adımlarının doğru sırayla yapılması daha güvenilir sonuç sağlar. En iyi özet hangisidir?",
    dimension: "SOZEL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "En önemli şey işlemi en hızlı tamamlamaktır." },
      { key: "B", text: "Kontroller yalnız hata çıkınca yapılmalıdır." },
      { key: "C", text: "Hızın yanında doğru sıra ve kontrol de önemlidir." },
      { key: "D", text: "Kayıt tutmak gereksizdir." },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: B, D, F, H, ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "I" },
      { key: "B", text: "J" },
      { key: "C", text: "K" },
      { key: "D", text: "L" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: ▲ ■ ▲ ■ ▲ ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "▲" },
      { key: "B", text: "■" },
      { key: "C", text: "●" },
      { key: "D", text: "◆" },
    ],
    correctKey: "B",
  },
  {
    text: "4A, 8B, 12C, 16D dizisinde sıradaki öğe hangisidir?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "18E" },
      { key: "B", text: "20D" },
      { key: "C", text: "20E" },
      { key: "D", text: "24E" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kuralda A=5, B=10, C=15, D=20 ise F'nin değeri kaçtır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "25" },
      { key: "B", text: "30" },
      { key: "C", text: "35" },
      { key: "D", text: "40" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 4, 8, 13, 19, 26, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "32" },
      { key: "B", text: "33" },
      { key: "C", text: "34" },
      { key: "D", text: "35" },
    ],
    correctKey: "C",
  },
  {
    text: "GH → HG, KL → LK kuralına göre MN nasıl yazılır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "MN" },
      { key: "B", text: "NM" },
      { key: "C", text: "MM" },
      { key: "D", text: "NN" },
    ],
    correctKey: "B",
  },
  {
    text: "Her sayı önce 3 ile çarpılıyor, sonra 1 ekleniyor. 5 sayısına uygulanırsa sonuç kaç olur?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "14" },
      { key: "B", text: "15" },
      { key: "C", text: "16" },
      { key: "D", text: "18" },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: Z, W, T, Q, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "N" },
      { key: "B", text: "O" },
      { key: "C", text: "P" },
      { key: "D", text: "M" },
    ],
    correctKey: "A",
  },
  {
    text: "Diziyi tamamlayın: 3, 6, 18, 72, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "144" },
      { key: "B", text: "216" },
      { key: "C", text: "288" },
      { key: "D", text: "360" },
    ],
    correctKey: "D",
  },
  {
    text: "Dizide sıradaki sayı hangisidir? 3, 4, 7, 11, 18, 29, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "40" },
      { key: "B", text: "43" },
      { key: "C", text: "47" },
      { key: "D", text: "51" },
    ],
    correctKey: "C",
  },
  {
    text: 'Hangisi "LAB-6934-R" koduyla birebir aynıdır?',
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "LAB-6934-R" },
      { key: "B", text: "LAB-6394-R" },
      { key: "C", text: "LAB-6934-P" },
      { key: "D", text: "LAB-693A-R" },
    ],
    correctKey: "A",
  },
  {
    text: "Şu dizide L harfi kaç kez geçmektedir? L K R L T L K L M T L",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangisi diğerlerinden farklı yazılmıştır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "NUMUNE" },
      { key: "B", text: "NUMUNE" },
      { key: "C", text: "NUMUEN" },
      { key: "D", text: "NUMUNE" },
    ],
    correctKey: "C",
  },
  {
    text: "Kaç kod tamamen aynıdır? Liste 1: LB-214 / NM-583 / KR-407 / TR-625. Liste 2: LB-214 / NM-538 / KR-407 / TR-652.",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: 'Hangisi "LB-8305-B2" koduyla aynı değildir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "LB-8305-B2" },
      { key: "B", text: "LB-8305-B2" },
      { key: "C", text: "LB-8035-B2" },
      { key: "D", text: "LB-8305-B2" },
    ],
    correctKey: "C",
  },
  {
    text: "Şu dizide 7 rakamı kaç kez geçmektedir? 7 3 7 5 1 7 6 2 7 4 7",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangi sayı grubunun rakam sırası diğerlerinden farklıdır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "58324" },
      { key: "B", text: "58324" },
      { key: "C", text: "53824" },
      { key: "D", text: "58324" },
    ],
    correctKey: "C",
  },
  {
    text: "127, 172, 217, 271, 712, 721 değerlerinin kaç tanesi 7 rakamıyla başlamaktadır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: '"LB7-N36-R" kodunun aynısı hangisidir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "LB7-N63-R" },
      { key: "B", text: "LB7-N36-R" },
      { key: "C", text: "LB7-M36-R" },
      { key: "D", text: "LB7-N36-K" },
    ],
    correctKey: "B",
  },
  {
    text: "İki satır arasında kaç karakter farklıdır? A: L7K4N8R2T5  B: L7M4N3R2T9",
    dimension: "DIKKAT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "2" },
      { key: "B", text: "3" },
      { key: "C", text: "4" },
      { key: "D", text: "5" },
    ],
    correctKey: "B",
  },
];