export type MechanicalAbilityItem = {
  text: string;
  dimension:
    | "SAYISAL"
    | "SOZEL"
    | "SOYUT"
    | "DIKKAT";
  difficulty:
    | "KOLAY"
    | "ORTA"
    | "ZOR";
  options: {
    key: string;
    text: string;
  }[];
  correctKey: string;
};

export const MECHANICAL_MAINTENANCE_ABILITY_ITEMS_A: MechanicalAbilityItem[] = [
  {
    text: "Bir bakım alanında 7 kutunun her birinde 12 bağlantı parçası vardır. Toplam kaç parça vardır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "72" },
      { key: "B", text: "84" },
      { key: "C", text: "92" },
      { key: "D", text: "96" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir çalışma saat 08:00'de başlayıp 11:30'da mola veriyor. Mola öncesinde kaç saat çalışılmıştır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "3,5" },
      { key: "C", text: "4" },
      { key: "D", text: "4,5" },
    ],
    correctKey: "B",
  },
  {
    text: "Kontrol edilmesi gereken 160 parçanın 40 tanesi kontrol edilmiştir. Parçaların yüzde kaçı kontrol edilmiştir?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "Üç farklı ekipman için yapılan kontroller 35, 45 ve 40 dakika sürmüştür. Ortalama kontrol süresi kaç dakikadır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "35" },
      { key: "B", text: "40" },
      { key: "C", text: "42" },
      { key: "D", text: "45" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir malzemeden başlangıçta 80 adet vardır. Yeni gelen malzemelerle sayı 100'e çıkmıştır. Miktar yüzde kaç artmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "6 çalışan bir işi eşit paylaşarak kişi başına 16 parça kontrol ediyor. Aynı toplam iş 8 çalışan arasında eşit paylaştırılırsa kişi başına kaç parça düşer?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "10" },
      { key: "B", text: "12" },
      { key: "C", text: "14" },
      { key: "D", text: "16" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir depoda 250 bağlantı elemanı vardır. 65'i bir işte, 45'i başka bir işte kullanılmıştır. Kaç adet kalmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "130" },
      { key: "B", text: "135" },
      { key: "C", text: "140" },
      { key: "D", text: "145" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kontrol işlemi 24 dakika sürüyor. Aynı süreyle art arda 5 kontrol yapılırsa toplam süre kaç saattir?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1 saat 40 dakika" },
      { key: "B", text: "1 saat 50 dakika" },
      { key: "C", text: "2 saat" },
      { key: "D", text: "2 saat 10 dakika" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir göstergenin değeri 200'den 170'e düşmüştür. Azalma oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%10" },
      { key: "B", text: "%12" },
      { key: "C", text: "%15" },
      { key: "D", text: "%20" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir bakım listesindeki işlerin ilk gün %25'i tamamlanıyor. İkinci gün kalan işlerin %40'ı tamamlanıyor. İki gün sonunda toplam işlerin yüzde kaçı tamamlanmıştır?",
    dimension: "SAYISAL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "%45" },
      { key: "B", text: "%50" },
      { key: "C", text: "%55" },
      { key: "D", text: "%65" },
    ],
    correctKey: "C",
  },
  {
    text: "\"Kontrol etmek\" ifadesine en yakın anlam hangisidir?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "İncelemek" },
      { key: "B", text: "Beklemek" },
      { key: "C", text: "Taşımak" },
      { key: "D", text: "Saklamak" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışmaya başlamadan önce verilen bakım talimatını ______.",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "değiştirmeliyiz" },
      { key: "B", text: "okumalıyız" },
      { key: "C", text: "kaldırmalıyız" },
      { key: "D", text: "ertelemeliyiz" },
    ],
    correctKey: "B",
  },
  {
    text: "Hangisi diğerlerinden farklı bir gruptadır?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Cıvata" },
      { key: "B", text: "Somun" },
      { key: "C", text: "Pul" },
      { key: "D", text: "Baret" },
    ],
    correctKey: "D",
  },
  {
    text: "\"Kontrol – Hata\" ilişkisine en yakın ilişki hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İnceleme – Eksiklik" },
      { key: "B", text: "Hız – Bekleme" },
      { key: "C", text: "Başlangıç – Bitiş" },
      { key: "D", text: "Gürültü – Sessizlik" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışan, yapacağı işlemin sırasından emin değildir. İşe başlamadan önce sorumlusuna danışır. Bu davranıştan hangi sonuç çıkarılır?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İşi yapmak istememektedir." },
      { key: "B", text: "Doğru yöntemi netleştirmektedir." },
      { key: "C", text: "İşi başkasına bırakmaktadır." },
      { key: "D", text: "Zaman kaybetmektedir." },
    ],
    correctKey: "B",
  },
  {
    text: "\"Uygunsuzluk\" sözcüğüne en yakın ifade hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Beklenenden sapma" },
      { key: "B", text: "Hızlı çalışma" },
      { key: "C", text: "İş bölümü" },
      { key: "D", text: "Dinlenme" },
    ],
    correctKey: "A",
  },
  {
    text: "\"önce / kontrol / çalıştırmadan / ekipmanı / et\" kelimeleriyle kurulacak anlamlı cümlenin ilk kelimesi hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Önce" },
      { key: "B", text: "Kontrol" },
      { key: "C", text: "Çalıştırmadan" },
      { key: "D", text: "Ekipmanı" },
    ],
    correctKey: "C",
  },
  {
    text: "Talimatta \"İş tamamlandığında kullanılan araçları belirlenen yere bırakınız.\" yazıyor. Çalışan ne yapmalıdır?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Araçları çalışma alanında bırakmalı" },
      { key: "B", text: "Araçları belirlenen yere koymalı" },
      { key: "C", text: "Başka çalışana vermeli" },
      { key: "D", text: "Talimatı dikkate almamalı" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir ekipte yapılan işlerin ve tespit edilen eksikliklerin kaydedilmesi, sonraki çalışmada ne yapıldığının anlaşılmasını kolaylaştırır. Ana düşünce nedir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Her iş uzun sürer." },
      { key: "B", text: "Kayıt tutmak işin takibini kolaylaştırır." },
      { key: "C", text: "Eksiklikler kaydedilmemelidir." },
      { key: "D", text: "Çalışanlar yalnız çalışmalıdır." },
    ],
    correctKey: "B",
  },
  {
    text: "Bir ekipmanın tekrar çalıştırılması işi hızlandırabilir. Ancak gerekli kontroller tamamlanmadan çalıştırılması yeni sorunlara ve güvenlik risklerine yol açabilir. Bu nedenle çalışma, hız kadar doğru sıra ve kontrol gerektirir. En iyi özet hangisidir?",
    dimension: "SOZEL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "Ekipman mümkün olduğunca hızlı çalıştırılmalıdır." },
      { key: "B", text: "Kontrol yalnız sorun çıkınca yapılmalıdır." },
      { key: "C", text: "Hızın yanında doğru işlem sırası ve kontrol önemlidir." },
      { key: "D", text: "Kontroller işi gereksiz yere uzatır." },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: C, E, G, I, ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "J" },
      { key: "B", text: "K" },
      { key: "C", text: "L" },
      { key: "D", text: "M" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: ● ■ ● ■ ● ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "●" },
      { key: "B", text: "■" },
      { key: "C", text: "▲" },
      { key: "D", text: "◆" },
    ],
    correctKey: "B",
  },
  {
    text: "4A, 8B, 12C, 16D dizisinde sıradaki öğe hangisidir?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "18E" },
      { key: "B", text: "20D" },
      { key: "C", text: "20E" },
      { key: "D", text: "24E" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kuralda A=5, B=10, C=15, D=20 ise F'nin değeri kaçtır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "25" },
      { key: "B", text: "30" },
      { key: "C", text: "35" },
      { key: "D", text: "40" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 4, 7, 11, 16, 22, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "28" },
      { key: "B", text: "29" },
      { key: "C", text: "30" },
      { key: "D", text: "31" },
    ],
    correctKey: "B",
  },
  {
    text: "AB → BA, CD → DC kuralına göre GH nasıl yazılır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "HG" },
      { key: "B", text: "GH" },
      { key: "C", text: "GG" },
      { key: "D", text: "HH" },
    ],
    correctKey: "A",
  },
  {
    text: "Bir kuralda her sayı önce 2 ile çarpılıyor, sonra 3 ekleniyor. 7 sayısına bu kural uygulanırsa sonuç kaç olur?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "14" },
      { key: "B", text: "15" },
      { key: "C", text: "17" },
      { key: "D", text: "20" },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: X, U, R, O, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "M" },
      { key: "B", text: "L" },
      { key: "C", text: "K" },
      { key: "D", text: "N" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 3, 6, 18, 72, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "144" },
      { key: "B", text: "216" },
      { key: "C", text: "288" },
      { key: "D", text: "360" },
    ],
    correctKey: "D",
  },
  {
    text: "Dizide sıradaki sayı hangisidir? 2, 5, 7, 12, 19, 31, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "43" },
      { key: "B", text: "48" },
      { key: "C", text: "50" },
      { key: "D", text: "52" },
    ],
    correctKey: "C",
  },
    {
    text: "Aşağıdaki seçeneklerden hangisi \"MB-4827-K\" koduyla birebir aynıdır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "MB-4827-K" },
      { key: "B", text: "MB-4287-K" },
      { key: "C", text: "MB-4827-X" },
      { key: "D", text: "MB-482T-K" },
    ],
    correctKey: "A",
  },
  {
    text: "Şu dizide M harfi kaç kez geçmektedir? M K M R T M K R M T M",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki kelimelerden hangisi diğerlerinden farklı yazılmıştır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "RULMAN" },
      { key: "B", text: "RULMAN" },
      { key: "C", text: "RULMNA" },
      { key: "D", text: "RULMAN" },
    ],
    correctKey: "C",
  },
  {
    text: "İki kod listesi karşılaştırılıyor. Kaç satır tamamen aynıdır? Liste 1: BK-214 / ML-583 / PN-407 / XR-625. Liste 2: BK-214 / ML-538 / PN-407 / XR-652.",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki seçeneklerden hangisi \"MK-7315-A4\" koduyla aynı değildir?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "MK-7315-A4" },
      { key: "B", text: "MK-7315-A4" },
      { key: "C", text: "MK-7135-A4" },
      { key: "D", text: "MK-7315-A4" },
    ],
    correctKey: "C",
  },
  {
    text: "Şu dizide 8 rakamı kaç kez geçmektedir? 8 3 5 8 1 8 6 2 8 8 4 7",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki sayı gruplarından hangisinde rakamların sırası diğerlerinden farklıdır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "47216" },
      { key: "B", text: "47216" },
      { key: "C", text: "42716" },
      { key: "D", text: "47216" },
    ],
    correctKey: "C",
  },
  {
    text: "314, 341, 413, 431, 134, 143 değerlerinin kaç tanesi 4 rakamıyla başlamaktadır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: "\"BK7-M25-R\" kodunun aynısı hangisidir?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "BK7-M52-R" },
      { key: "B", text: "BK7-M25-R" },
      { key: "C", text: "BK7-N25-R" },
      { key: "D", text: "BK7-M25-K" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki iki satır arasında kaç karakter farklıdır? A: M7K4P8R2T5  B: M7R4P3R2T9",
    dimension: "DIKKAT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "2" },
      { key: "B", text: "3" },
      { key: "C", text: "4" },
      { key: "D", text: "5" },
    ],
    correctKey: "B",
  },
    ];

export const MECHANICAL_MAINTENANCE_ABILITY_ITEMS_B: MechanicalAbilityItem[] = [
  {
    text: "Bir bakım ekibi 6 kutunun her birinde 15 parça sayıyor. Toplam kaç parça vardır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "80" },
      { key: "B", text: "90" },
      { key: "C", text: "95" },
      { key: "D", text: "100" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir çalışma 09:00'da başlayıp 13:00'te tamamlanıyor. Çalışma kaç saat sürmüştür?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "3,5" },
      { key: "C", text: "4" },
      { key: "D", text: "4,5" },
    ],
    correctKey: "C",
  },
  {
    text: "200 parçanın 50 tanesi ayrılmıştır. Ayrılan parçalar toplamın yüzde kaçıdır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "Üç bakım işlemi 30, 45 ve 45 dakika sürmüştür. Ortalama süre kaç dakikadır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "35" },
      { key: "B", text: "40" },
      { key: "C", text: "42" },
      { key: "D", text: "45" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir malzemenin miktarı 120 adetten 150 adede çıkmıştır. Artış oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%35" },
    ],
    correctKey: "B",
  },
  {
    text: "5 çalışan bir işi eşit paylaşarak kişi başına 24 parça kontrol ediyor. Aynı iş 8 çalışan arasında eşit paylaşılırsa kişi başına kaç parça düşer?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "12" },
      { key: "B", text: "15" },
      { key: "C", text: "18" },
      { key: "D", text: "20" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir depoda 320 parça vardır. 85 parça kullanılmış, ardından 25 parça daha kullanılmıştır. Kaç parça kalmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "200" },
      { key: "B", text: "205" },
      { key: "C", text: "210" },
      { key: "D", text: "215" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kontrol 18 dakika sürüyor. Aynı süreyle 5 kontrol yapılırsa toplam süre nedir?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1 saat 20 dakika" },
      { key: "B", text: "1 saat 30 dakika" },
      { key: "C", text: "1 saat 40 dakika" },
      { key: "D", text: "2 saat" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir göstergenin değeri 250'den 200'e düşmüştür. Azalma oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%15" },
      { key: "B", text: "%20" },
      { key: "C", text: "%25" },
      { key: "D", text: "%30" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir bakım planının ilk gün %40'ı tamamlanıyor. İkinci gün kalan işin %50'si tamamlanıyor. İki gün sonunda toplam işin yüzde kaçı tamamlanmıştır?",
    dimension: "SAYISAL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "%60" },
      { key: "B", text: "%65" },
      { key: "C", text: "%70" },
      { key: "D", text: "%80" },
    ],
    correctKey: "C",
  },
  {
    text: "\"Talimat\" kelimesine en yakın anlam hangisidir?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Yönerge" },
      { key: "B", text: "Malzeme" },
      { key: "C", text: "Dinlenme" },
      { key: "D", text: "Ölçü" },
    ],
    correctKey: "A",
  },
  {
    text: "İşe başlamadan önce çalışma alanını ______.",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "kontrol etmeliyiz" },
      { key: "B", text: "terk etmeliyiz" },
      { key: "C", text: "dağıtmalıyız" },
      { key: "D", text: "kapatmalıyız" },
    ],
    correctKey: "A",
  },
  {
    text: "Hangisi diğerlerinden farklıdır?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Cıvata" },
      { key: "B", text: "Somun" },
      { key: "C", text: "Pul" },
      { key: "D", text: "Eldiven" },
    ],
    correctKey: "D",
  },
  {
    text: "\"Planlama – Hazırlık\" ilişkisine en yakın ilişki hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Kontrol – Önlem" },
      { key: "B", text: "Hız – Bekleme" },
      { key: "C", text: "Gürültü – Sessizlik" },
      { key: "D", text: "Başlangıç – Bitiş" },
    ],
    correctKey: "A",
  },
  {
    text: "Çalışan, bakım işine başlamadan önce gerekli parçaların tam olup olmadığını kontrol ediyor. Bu davranışın temel amacı nedir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "İşi geciktirmek" },
      { key: "B", text: "İşe hazırlıklı başlamak" },
      { key: "C", text: "Sorumluluğu devretmek" },
      { key: "D", text: "Çalışmayı bırakmak" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Tedbir\" kelimesine en yakın anlam hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Önlem" },
      { key: "B", text: "Bekleme" },
      { key: "C", text: "Gecikme" },
      { key: "D", text: "Değişiklik" },
    ],
    correctKey: "A",
  },
  {
    text: "\"önce / çalışma / alanını / düzenle / işe\" kelimeleriyle kurulacak anlamlı cümlenin ilk kelimesi hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Önce" },
      { key: "B", text: "Çalışma" },
      { key: "C", text: "Alanını" },
      { key: "D", text: "İşe" },
    ],
    correctKey: "A",
  },
  {
    text: "İş bittikten sonra kullanılan malzemelerin kayıt altına alınması neden önemlidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Malzemelerin takibini kolaylaştırır." },
      { key: "B", text: "İşi daha zor hale getirir." },
      { key: "C", text: "Çalışmayı tamamen durdurur." },
      { key: "D", text: "Malzemelerin kullanılmasını engeller." },
    ],
    correctKey: "A",
  },
  {
    text: "Bir çalışan, yaptığı kontrolde beklenmeyen bir durum fark ediyor ve işlemi sürdürmeden önce sorumlusuna bilgi veriyor. Bu davranış neyi gösterir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Kuralları dikkate aldığını" },
      { key: "B", text: "İşi yapmak istemediğini" },
      { key: "C", text: "Zaman geçirmek istediğini" },
      { key: "D", text: "Sorumluluktan kaçtığını" },
    ],
    correctKey: "A",
  },
  {
    text: "Bir bakım işinde hızlı olmak tek başına yeterli değildir. İşin doğru sırayla ve belirlenen kurallara uygun yapılması da gerekir. Bu ifadeyi en iyi özetleyen seçenek hangisidir?",
    dimension: "SOZEL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "En önemli şey işi en hızlı tamamlamaktır." },
      { key: "B", text: "Kurallara uymak çalışmayı gereksiz yere uzatır." },
      { key: "C", text: "Hız kadar doğru işlem ve kurallara uygunluk da önemlidir." },
      { key: "D", text: "Kontroller yalnız sorun çıktığında yapılmalıdır." },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: B, D, F, H, ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "I" },
      { key: "B", text: "J" },
      { key: "C", text: "K" },
      { key: "D", text: "L" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: ▲ ● ▲ ● ▲ ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "▲" },
      { key: "B", text: "●" },
      { key: "C", text: "■" },
      { key: "D", text: "◆" },
    ],
    correctKey: "B",
  },
  {
    text: "3A, 6B, 9C, 12D dizisinde sıradaki öğe hangisidir?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "14E" },
      { key: "B", text: "15D" },
      { key: "C", text: "15E" },
      { key: "D", text: "18E" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kuralda A=3, B=6, C=9, D=12 ise G'nin değeri kaçtır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "18" },
      { key: "B", text: "21" },
      { key: "C", text: "24" },
      { key: "D", text: "27" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 5, 9, 14, 20, 27, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "33" },
      { key: "B", text: "34" },
      { key: "C", text: "35" },
      { key: "D", text: "36" },
    ],
    correctKey: "C",
  },
  {
    text: "KL → LK, MN → NM kuralına göre PR nasıl yazılır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "PR" },
      { key: "B", text: "RP" },
      { key: "C", text: "PP" },
      { key: "D", text: "RR" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kuralda her sayı önce 3 ile çarpılıyor, sonra 2 çıkarılıyor. 6 sayısına uygulanırsa sonuç kaç olur?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "14" },
      { key: "B", text: "16" },
      { key: "C", text: "18" },
      { key: "D", text: "20" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: Y, V, S, P, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "M" },
      { key: "B", text: "N" },
      { key: "C", text: "O" },
      { key: "D", text: "L" },
    ],
    correctKey: "A",
  },
  {
    text: "Diziyi tamamlayın: 2, 6, 24, 120, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "360" },
      { key: "B", text: "480" },
      { key: "C", text: "600" },
      { key: "D", text: "720" },
    ],
    correctKey: "D",
  },
  {
    text: "Dizide sıradaki sayı hangisidir? 4, 7, 11, 18, 29, 47, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "65" },
      { key: "B", text: "72" },
      { key: "C", text: "76" },
      { key: "D", text: "78" },
    ],
    correctKey: "C",
  },
  {
    text: 'Aşağıdaki seçeneklerden hangisi "EB-5938-M" koduyla birebir aynıdır?',
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "EB-5938-M" },
      { key: "B", text: "EB-5398-M" },
      { key: "C", text: "EB-5938-N" },
      { key: "D", text: "EB-593B-M" },
    ],
    correctKey: "A",
  },
  {
    text: "Şu dizide 7 rakamı kaç kez geçmektedir? 7 2 4 7 9 1 7 5 3 7 8",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "4" },
      { key: "C", text: "5" },
      { key: "D", text: "6" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki kelimelerden hangisi diğerlerinden farklı yazılmıştır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "MOTOR" },
      { key: "B", text: "MOTOR" },
      { key: "C", text: "MOTRO" },
      { key: "D", text: "MOTOR" },
    ],
    correctKey: "C",
  },
  {
    text: "İki kod listesi karşılaştırılıyor. Kaç satır tamamen aynıdır? Liste 1: MK-214 / AB-583 / RT-407 / KL-625. Liste 2: MK-214 / AB-538 / RT-407 / KL-652.",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: 'Aşağıdaki seçeneklerden hangisi "BK-6402-P3" koduyla aynı değildir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "BK-6402-P3" },
      { key: "B", text: "BK-6402-P3" },
      { key: "C", text: "BK-6042-P3" },
      { key: "D", text: "BK-6402-P3" },
    ],
    correctKey: "C",
  },
  {
    text: "Şu dizide K harfi kaç kez geçmektedir? K R M K T K P R K M T K",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki sayı gruplarından hangisinde rakamların sırası diğerlerinden farklıdır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "58321" },
      { key: "B", text: "58321" },
      { key: "C", text: "53821" },
      { key: "D", text: "58321" },
    ],
    correctKey: "C",
  },
  {
    text: "124, 142, 214, 241, 412, 421 değerlerinin kaç tanesi 4 rakamıyla başlamaktadır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: '"MK8-R31-T" kodunun aynısı hangisidir?',
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "MK8-R13-T" },
      { key: "B", text: "MK8-R31-T" },
      { key: "C", text: "MK8-T31-R" },
      { key: "D", text: "MK8-R31-P" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki iki satır arasında kaç karakter farklıdır? A: E4K7M2R9P6  B: E4M7M5R9P8",
    dimension: "DIKKAT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "2" },
      { key: "B", text: "3" },
      { key: "C", text: "4" },
      { key: "D", text: "5" },
    ],
    correctKey: "C",
  },
];