export const NEW_PRODUCTION_ABILITY_ITEMS_FORM_B = [
  {
    text: "Bir palette 16 kutu, her kutuda 6 parça bulunmaktadır. Toplam kaç parça vardır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "86" },
      { key: "B", text: "92" },
      { key: "C", text: "96" },
      { key: "D", text: "106" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir çalışan saat 07:30'da işe başlayıp 11:30'da mola veriyor. Mola öncesinde kaç saat çalışmıştır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "3,5" },
      { key: "C", text: "4" },
      { key: "D", text: "4,5" },
    ],
    correctKey: "C",
  },
  {
    text: "240 parçanın 60 tanesi kontrol edilmiştir. Kontrol edilen parçalar toplamın yüzde kaçıdır?",
    dimension: "SAYISAL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "%20" },
      { key: "B", text: "%25" },
      { key: "C", text: "%30" },
      { key: "D", text: "%40" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir ekip üç saatte sırasıyla 42, 48 ve 45 parça hazırlamıştır. Saatlik ortalama kaç parçadır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "43" },
      { key: "B", text: "44" },
      { key: "C", text: "45" },
      { key: "D", text: "46" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir malzemenin miktarı 500 kg'dan 575 kg'a çıkmıştır. Artış oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%10" },
      { key: "B", text: "%12" },
      { key: "C", text: "%15" },
      { key: "D", text: "%20" },
    ],
    correctKey: "C",
  },
  {
    text: "8 çalışan bir işi eşit paylaşarak kişi başına 15 parça hazırlıyor. Aynı toplam iş 6 çalışan arasında eşit paylaştırılırsa kişi başına kaç parça düşer?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "18" },
      { key: "B", text: "20" },
      { key: "C", text: "22" },
      { key: "D", text: "24" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir göstergenin değeri 120'den 102'ye düşmüştür. Azalma oranı yüzde kaçtır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "%10" },
      { key: "B", text: "%12" },
      { key: "C", text: "%15" },
      { key: "D", text: "%18" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir işlem 18 dakika sürmektedir. Aynı süreyle art arda 5 işlem yapılırsa toplam süre kaç saat kaç dakika olur?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1 saat 20 dakika" },
      { key: "B", text: "1 saat 30 dakika" },
      { key: "C", text: "1 saat 40 dakika" },
      { key: "D", text: "1 saat 50 dakika" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir depoda 480 parça vardır. İlk vardiyada 125, ikinci vardiyada 95 parça kullanılmıştır. Depoda kaç parça kalmıştır?",
    dimension: "SAYISAL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "250" },
      { key: "B", text: "255" },
      { key: "C", text: "260" },
      { key: "D", text: "270" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir işin ilk gün %40'ı tamamlanıyor. İkinci gün kalan işin %25'i tamamlanıyor. İki gün sonunda işin yüzde kaçı tamamlanmıştır?",
    dimension: "SAYISAL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "%50" },
      { key: "B", text: "%55" },
      { key: "C", text: "%60" },
      { key: "D", text: "%65" },
    ],
    correctKey: "B",
  },

  {
    text: "\"Özenli\" kelimesine anlamca en yakın seçenek hangisidir?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Dikkatli" },
      { key: "B", text: "Hızlı" },
      { key: "C", text: "Güçlü" },
      { key: "D", text: "Sessiz" },
    ],
    correctKey: "A",
  },
  {
    text: "\"Çalışmaya başlamadan önce verilen talimatları ______.\" cümlesini en uygun tamamlayan ifade hangisidir?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "değiştirmeliyiz" },
      { key: "B", text: "okumalıyız" },
      { key: "C", text: "ertelemeliyiz" },
      { key: "D", text: "unutmalıyız" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdakilerden hangisi diğerlerinden farklı bir gruptadır?",
    dimension: "SOZEL",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "Pense" },
      { key: "B", text: "Anahtar" },
      { key: "C", text: "Tornavida" },
      { key: "D", text: "Baret" },
    ],
    correctKey: "D",
  },
  {
    text: "\"Planlama – Düzen\" ilişkisine en yakın ilişki hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Kontrol – Doğruluk" },
      { key: "B", text: "Hız – Bekleme" },
      { key: "C", text: "Gürültü – Sessizlik" },
      { key: "D", text: "Başlangıç – Gecikme" },
    ],
    correctKey: "A",
  },
  {
    text: "\"Çalışan kendisine verilen görevi tam olarak anlamadığını fark etti. İşe başlamadan önce sorumlusundan açıklama istedi.\" Bu davranıştan hangi sonuç çıkarılabilir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Çalışan görevi yapmak istememektedir." },
      { key: "B", text: "Çalışan işi başkasına bırakmıştır." },
      { key: "C", text: "Çalışan doğru anlamadan işe başlamamıştır." },
      { key: "D", text: "Çalışan işi geciktirmeyi amaçlamıştır." },
    ],
    correctKey: "C",
  },
  {
    text: "\"Uygun\" kelimesine anlamca en yakın seçenek hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Elverişli" },
      { key: "B", text: "Eksik" },
      { key: "C", text: "Karmaşık" },
      { key: "D", text: "Uzak" },
    ],
    correctKey: "A",
  },
  {
    text: "\"sonra / yerine / kullandığın / işi / ekipmanı / koy\" kelimeleriyle oluşturulacak anlamlı cümlenin ilk kelimesi hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Sonra" },
      { key: "B", text: "Yerine" },
      { key: "C", text: "Kullandığın" },
      { key: "D", text: "İşi" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir iş talimatında, \"Kontrol sırasında tespit edilen uygunsuzlukları sorumlu kişiye bildiriniz.\" yazmaktadır. Buna göre çalışan ne yapmalıdır?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Uygunsuzluğu kendi başına gizlice düzeltmelidir." },
      { key: "B", text: "Uygunsuzluğu görmezden gelmelidir." },
      { key: "C", text: "Tespit ettiği uygunsuzluğu sorumlu kişiye bildirmelidir." },
      { key: "D", text: "Kontrolü sonlandırıp işyerinden ayrılmalıdır." },
    ],
    correctKey: "C",
  },
  {
    text: "\"Bir ekipte herkes kullandığı araç ve malzemeleri belirlenen yerde tutar. Böylece ihtiyaç halinde gerekli ekipmana hızlıca ulaşılabilir ve çalışma alanındaki karışıklık azalır.\" Metnin ana düşüncesi hangisidir?",
    dimension: "SOZEL",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Araçların sayısı artırılmalıdır." },
      { key: "B", text: "Düzenli çalışma işin yürütülmesini kolaylaştırır." },
      { key: "C", text: "Her çalışan farklı ekipman kullanmalıdır." },
      { key: "D", text: "Çalışma alanları mümkün olduğunca küçük olmalıdır." },
    ],
    correctKey: "B",
  },
  {
    text: "\"Bir işi zamanında tamamlamak önemlidir. Ancak zaman kazanmak amacıyla gerekli kontrollerin atlanması, daha sonra hata ve iş kaybına neden olabilir. Bu nedenle verimlilik, yalnızca hızlı çalışmak değil; işi doğru yöntemle ve gerekli kontrolleri yaparak tamamlamaktır.\" Bu parçayı en iyi özetleyen seçenek hangisidir?",
    dimension: "SOZEL",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "Hızlı çalışan kişi her zaman daha verimlidir." },
      { key: "B", text: "Kontroller yalnızca iş bittikten sonra yapılmalıdır." },
      { key: "C", text: "Verimlilik, hızın yanında doğru çalışma ve gerekli kontrolleri de gerektirir." },
      { key: "D", text: "İşin tamamlanma süresi önemli değildir." },
    ],
    correctKey: "C",
  },

  {
    text: "Diziyi tamamlayın: B, D, F, H, ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "I" },
      { key: "B", text: "J" },
      { key: "C", text: "K" },
      { key: "D", text: "L" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: ▲ ■ ▲ ■ ▲ ...",
    dimension: "SOYUT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "▲" },
      { key: "B", text: "■" },
      { key: "C", text: "●" },
      { key: "D", text: "◆" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 3A, 6B, 9C, 12D, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "14E" },
      { key: "B", text: "15D" },
      { key: "C", text: "15E" },
      { key: "D", text: "16E" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir kodlama kuralında A=3, B=6, C=9, D=12 ise G harfinin değeri kaçtır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "18" },
      { key: "B", text: "21" },
      { key: "C", text: "24" },
      { key: "D", text: "27" },
    ],
    correctKey: "B",
  },
  {
    text: "Diziyi tamamlayın: 3, 7, 12, 18, 25, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "31" },
      { key: "B", text: "32" },
      { key: "C", text: "33" },
      { key: "D", text: "34" },
    ],
    correctKey: "C",
  },
  {
    text: "ABC → CBA, DEF → FED kuralına göre GHI nasıl yazılır?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "HIG" },
      { key: "B", text: "IHG" },
      { key: "C", text: "IGH" },
      { key: "D", text: "GIH" },
    ],
    correctKey: "B",
  },
  {
    text: "Bir kuralda her sayı önce 3 ile çarpılıyor, sonra 2 çıkarılıyor. 5 sayısına bu kural uygulanırsa sonuç kaç olur?",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "11" },
      { key: "B", text: "12" },
      { key: "C", text: "13" },
      { key: "D", text: "15" },
    ],
    correctKey: "C",
  },
  {
    text: "Diziyi tamamlayın: Y, V, S, P, ...",
    dimension: "SOYUT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "M" },
      { key: "B", text: "N" },
      { key: "C", text: "O" },
      { key: "D", text: "L" },
    ],
    correctKey: "A",
  },
  {
    text: "Diziyi tamamlayın: 2, 6, 24, 120, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "360" },
      { key: "B", text: "480" },
      { key: "C", text: "600" },
      { key: "D", text: "720" },
    ],
    correctKey: "D",
  },
  {
    text: "Dizide sıradaki sayı hangisidir? 4, 6, 10, 16, 26, 42, ...",
    dimension: "SOYUT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "58" },
      { key: "B", text: "62" },
      { key: "C", text: "68" },
      { key: "D", text: "72" },
    ],
    correctKey: "C",
  },

  {
    text: "Aşağıdaki seçeneklerden hangisi \"PK-6731-M\" koduyla birebir aynıdır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "PK-6731-M" },
      { key: "B", text: "PK-6371-M" },
      { key: "C", text: "PK-673I-M" },
      { key: "D", text: "PK-6731-N" },
    ],
    correctKey: "A",
  },
  {
    text: "Şu dizide 7 rakamı kaç kez geçmektedir? 7 3 7 5 2 7 8 7 1 6 7",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki kelimelerden hangisi diğerlerinden farklı yazılmıştır?",
    dimension: "DIKKAT",
    difficulty: "KOLAY",
    options: [
      { key: "A", text: "KONTROL" },
      { key: "B", text: "KONTROL" },
      { key: "C", text: "KONTORL" },
      { key: "D", text: "KONTROL" },
    ],
    correctKey: "C",
  },
  {
    text: "İki kod listesi karşılaştırılıyor. Kaç satır tamamen aynıdır? Liste 1: KP-216 / MR-745 / ST-308 / LN-552  Liste 2: KP-216 / MR-754 / ST-308 / LN-525",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdakilerden hangisi \"BZ-4816-C7\" koduyla aynı DEĞİLDİR?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "BZ-4816-C7" },
      { key: "B", text: "BZ-4816-C7" },
      { key: "C", text: "BZ-4861-C7" },
      { key: "D", text: "BZ-4816-C7" },
    ],
    correctKey: "C",
  },
  {
    text: "Şu harf dizisinde R harfi kaç kez geçmektedir? R T K R M R T R K M R T",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "4" },
      { key: "B", text: "5" },
      { key: "C", text: "6" },
      { key: "D", text: "7" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki sayı gruplarından hangisinde rakamların sırası diğerlerinden farklıdır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "63825" },
      { key: "B", text: "63825" },
      { key: "C", text: "68325" },
      { key: "D", text: "63825" },
    ],
    correctKey: "C",
  },
  {
    text: "Bir listede şu değerler vardır: 314, 341, 413, 431, 134, 143. Kaç değer 4 rakamıyla başlamaktadır?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" },
    ],
    correctKey: "B",
  },
  {
    text: "\"Q5T-M82-L\" kodunun karakter sırasını değiştirmeden aynısını gösteren seçenek hangisidir?",
    dimension: "DIKKAT",
    difficulty: "ORTA",
    options: [
      { key: "A", text: "Q5T-M28-L" },
      { key: "B", text: "Q5T-M82-L" },
      { key: "C", text: "Q5T-N82-L" },
      { key: "D", text: "QST-M82-L" },
    ],
    correctKey: "B",
  },
  {
    text: "Aşağıdaki iki satır karşılaştırıldığında kaç karakter farklıdır? A: T8K3M7P5R2  B: T8R3M4P5R9",
    dimension: "DIKKAT",
    difficulty: "ZOR",
    options: [
      { key: "A", text: "2" },
      { key: "B", text: "3" },
      { key: "C", text: "4" },
      { key: "D", text: "5" },
    ],
    correctKey: "B",
  },
] as const;
